### ISSUE TITLE
Unable to open

### ISSUE THREAD

**Issue by stxcks** [AtlasFn/atlas-issues#8]
I get the message that "Fortnite was not started correctly and needs to be closed. We recommend trying to launch the game using the Epic Games Launcher or contact player support." Please fix. This is AtlasFN v1.0.1 and I am on Windows 10 Pro.

**Comment by AlexDev404** [comment]
Thank you for your issue. Did you make sure to check that you are using the correct version of Fortnite? We recommend that you use Fortnite version 13.40. You can install this with EasyInstaller.
